"""Backtest report writer: turns metrics into a static HTML page.

The HTML is intentionally framework-free — no React, no Tailwind, no
CDN dependencies. It opens in any browser offline, viewable to a
recruiter who clicks a GitHub link without cloning or installing
anything. That's the "interview signal" the outside voice flagged as
strongest in OV-G.

Layout: title + summary tiles + ASCII equity curve + per-fill table.
The ASCII curve ships as <pre> text — a v2 could inline an SVG sparkline
but ASCII-first means no JS, no images, no scaling glitches.
"""
from __future__ import annotations

import html
from datetime import datetime, UTC


def _ascii_curve(equity_points: list[float], *, height: int = 16) -> str:
    """Render equity_points as an ASCII sparkline. Cheap, screenshot-safe."""
    if not equity_points:
        return "(no equity points)"
    lo = min(equity_points)
    hi = max(equity_points)
    span = hi - lo if hi > lo else 1.0
    n = len(equity_points)
    cols = min(80, n)  # cap width
    rows = [""] * height
    for i in range(cols):
        # Pick the equity point closest to column i.
        idx = int(i * (n - 1) / max(1, cols - 1))
        v = equity_points[idx]
        # Map to row: top = hi, bottom = lo.
        row = height - 1 - int((v - lo) / span * (height - 1))
        rows[row] = rows[row].ljust(i, " ") + "█"
    return "\n".join(rows)


def render_report(
    *,
    summary: dict,
    fills: list[dict],
    title: str,
    period_label: str,
) -> str:
    """Build the HTML body. Caller writes it to disk."""
    eq = summary["equity_curve"]
    eq_points = [p["equity_usdt"] for p in eq if "equity_usdt" in p]
    curve_text = _ascii_curve(eq_points)

    fills_rows = []
    for f in fills[-50:]:  # cap rows so the file stays small
        fills_rows.append(
            "<tr>"
            f"<td>{html.escape(str(f.get('ts_idx', '')))}</td>"
            f"<td>{html.escape(str(f.get('symbol', '')))}</td>"
            f"<td>{html.escape(str(f.get('side', '')))}</td>"
            f"<td>{f.get('qty', 0):.6f}</td>"
            f"<td>{f.get('price', 0):.2f}</td>"
            "</tr>"
        )
    fills_html = "\n".join(fills_rows)

    css = (
        "body{font-family:ui-monospace,Menlo,Consolas,monospace;"
        "max-width:960px;margin:24px auto;padding:0 16px;color:#222}"
        ".tiles{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}"
        ".tile{border:1px solid #ddd;padding:12px 16px;border-radius:6px;"
        "min-width:140px}"
        ".tile .v{font-size:24px;font-weight:600}"
        ".tile .l{color:#666;font-size:12px;text-transform:uppercase}"
        "pre{background:#fafafa;padding:12px;border-radius:6px;"
        "font-size:11px;line-height:1;overflow-x:auto}"
        "table{border-collapse:collapse;width:100%;font-size:13px;margin-top:16px}"
        "th,td{border-bottom:1px solid #eee;padding:6px 8px;text-align:left}"
        ".meta{color:#666;font-size:12px;margin-bottom:24px}"
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{html.escape(title)}</title>
<style>{css}</style>
</head>
<body>
<h1>{html.escape(title)}</h1>
<div class="meta">
  Period: {html.escape(period_label)} ·
  Generated: {datetime.now(UTC).isoformat(timespec='seconds')}Z
</div>

<div class="tiles">
  <div class="tile"><div class="v">{summary['final_equity_usdt']:.2f}</div><div class="l">Final equity (USDT)</div></div>
  <div class="tile"><div class="v">{summary['total_return_pct']:+.2f}%</div><div class="l">Total return</div></div>
  <div class="tile"><div class="v">{summary['sharpe_ratio']:.2f}</div><div class="l">Sharpe (annualised)</div></div>
  <div class="tile"><div class="v">{summary['max_drawdown_usdt']:.2f}</div><div class="l">Max drawdown (USDT)</div></div>
  <div class="tile"><div class="v">{summary['win_rate']*100:.1f}%</div><div class="l">Win rate (closed sells)</div></div>
  <div class="tile"><div class="v">{summary['n_fills']}</div><div class="l">Fills total</div></div>
  <div class="tile"><div class="v">{summary['n_sells']}</div><div class="l">Closed positions</div></div>
</div>

<h2>Equity curve</h2>
<pre>{html.escape(curve_text)}</pre>

<h2>Last {len(fills_rows)} fills</h2>
<table>
  <thead><tr><th>ts_idx</th><th>symbol</th><th>side</th><th>qty</th><th>price</th></tr></thead>
  <tbody>
{fills_html}
  </tbody>
</table>

<p class="meta">
  Generated by <code>app.backtest.report.render_report</code> ·
  Replays AIDecision.raw_response (no LLM calls) · Cost ~$0.
</p>
</body>
</html>
"""
